### ISSUE TITLE
USB-C Receptable to Mux Differential Pair Connections

### ISSUE THREAD

**Issue by stevenpickles** [MicroType-Engineering/MTE_USB_HUB#1]
It looks like the USB-C connector pins TX1+/- and TX2+/- are connected to the mux/demux TX2p/n and TX1p/n pins, respectively. The receive differential pairs are connected to their logically numbered pairs on the multiplexer.

![image](https://user-images.githubusercontent.com/9694960/112547077-a6e89700-8d90-11eb-9b20-f918bbd234e7.png)

**Comment by KyleHunter** [comment]
Good catch!

Commit fafc15b4c7f9c18acf140f8fb585da674bd36e69 closes #1
